name: License Check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install license-header-checker
        run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
      - name: Run license check
        run: ./bin/license-header-checker -a -r -i proto,vendor ./license_header.txt . go && [[ -z `git status -s` ]]